export const GET_ALL_CINEMAS = 'GET_ALL_CINEMAS';
export const SELECT_CINEMA = 'SELECT_CINEMA';
export const GET_ALL_MOVIES_IN_CINEMA = 'GET_ALL_MOVIES_IN_CINEMA';
export const UPCOMING_MOVIES = 'UPCOMING_MOVIES';
